# Generated by Django 5.2.1 on 2025-06-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_googledrivetoken_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleDriveToken',
        ),
    ]
