# Generated by Django 5.2.1 on 2025-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_googledrivetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
