# Generated by Django 5.2.1 on 2025-06-11 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
