# Generated by Django 5.2.1 on 2025-06-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_calendarevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
