# Generated by Django 5.2.1 on 2025-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_calendarevent_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='eventid',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
