# Generated by Django 5.0.7 on 2025-07-26 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_calendarevent_eventid_calendarevent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='platform',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
