# Generated by Django 5.0.7 on 2025-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_calendarevent_duration_calendarevent_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder',
            field=models.CharField(default='10 minutes', max_length=50),
        ),
    ]
