# Generated by Django 5.0.7 on 2025-07-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_calendarevent_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='duration',
            field=models.DurationField(),
        ),
    ]
